services:
  # ----------------------------
  # Broker Kafka
  # ----------------------------
  kafka:
    image: apache/kafka:3.9.0
    restart: unless-stopped
    ports:
      - "9096:9096"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://kafka:9096,CONTROLLER://kafka:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9096,EXTERNAL://127.0.0.1:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9096"
      CLUSTER_ID: "4L62IdtzT-makk48j9YgAg"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      # --- Tuning ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
      KAFKA_REQUEST_TIMEOUT_MS: 60000
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9096"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - sdcc_progetto

  # ----------------------------
  # Setup Kafka (Creazione Topic)
  # ----------------------------
  init-kafka:
    image: apache/kafka:3.9.0
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "/init-kafka.sh"]
    volumes:
      - ./kafka/init-kafka.sh:/init-kafka.sh:ro
    networks:
      - sdcc_progetto

  # ----------------------------
  # Generatore di Eventi (Go)
  # ----------------------------
  events-generator:
    build:
      context: .
      dockerfile: ./events-generator/Dockerfile
    container_name: events_generator
    restart: unless-stopped
    ports:
      - "50051:50051"
    environment:
      - KAFKA_BROKER=kafka:9096 # Usa la porta interna di Kafka
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=qwertyuiopo1
    depends_on:
      init-kafka:
        condition: service_completed_successfully # Attende la creazione dei Topic
      redis:
        condition: service_healthy
    networks:
      - sdcc_progetto
  # ----------------------------
  # Front-End (API Gateway)
  # ----------------------------
  front-end:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    container_name: front-end
    ports:
      - "8080:8080"
    environment:
      - GENERATOR_GRPC_HOST=events-generator:50051
      - SINK_GRPC_HOST=sink-service:50052
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=qwertyuiopo1
    depends_on:
      - events-generator
      - sink-service
      - redis
    networks:
      - sdcc_progetto
    restart: on-failure
  # ----------------------------
  # Servizio --> Ingestion-Service (Go)
  # ----------------------------
  ingestion-service:
    build:
      context: ./services/ingestion-service
      dockerfile: Dockerfile
    #container_name: ingestion_service
    restart: unless-stopped
    environment:
      - KAFKA_BROKER=kafka:9096 # Usa la porta interna di Kafka
    depends_on:
      init-kafka:
        condition: service_completed_successfully # Attende la creazione dei Topic
      events-generator:
        condition: service_started # Attende solo l'avvio e non la terminazione
    networks:
      - sdcc_progetto

  # ----------------------------
  # Database Time-Series (InfluxDB v2)
  # ----------------------------
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=sdcc_org
      - DOCKER_INFLUXDB_INIT_BUCKET=default
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - sdcc_progetto

  # ----------------------------
  # Setup Kafka (Creazione Topic)
  # ----------------------------
  init-influxdb:
    image: influxdb:2.7
    container_name: init_influxdb
    depends_on:
      influxdb:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      influx bucket create -n telemetry -o sdcc_org -t my-super-secret-token --host http://influxdb:8086 || true;
      influx bucket create -n measurement -o sdcc_org -t my-super-secret-token --host http://influxdb:8086 || true;
      echo 'Bucket telemetry e measurement verificati/creati con successo!';
      "
    networks:
      - sdcc_progetto

  # ----------------------------
  # Write Service (Go)
  # ----------------------------
  write-service:
    build:
      context: ./services/write-service
      dockerfile: Dockerfile
    container_name: write_service
    restart: unless-stopped
    environment:
      - KAFKA_BROKER=kafka:9096
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-token
      - INFLUXDB_ORGANIZATION=sdcc_org
      - INFLUXDB_BUCKET=telemetry
    depends_on:
      init-kafka:
        condition: service_completed_successfully
      init-influxdb:
        condition: service_completed_successfully
    networks:
      - sdcc_progetto

  # ----------------------------
  # Analyzer Service (Go)
  # ----------------------------
  analyzer-service:
    build:
      context: ./services/analyzer-service
      dockerfile: Dockerfile
    #container_name: analyzer_service
    restart: unless-stopped
    environment:
      - KAFKA_BROKER=kafka:9096
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=qwertyuiopo1
    depends_on:
      init-kafka:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - sdcc_progetto

  # ----------------------------
  # Decision Service (Go)
  # ----------------------------
  decision-service:
    build:
      context: .
      dockerfile: services/decision-service/Dockerfile
    #container_name: decision_service
    restart: unless-stopped
    ports:
      - "2112"
    environment:
      - KAFKA_BROKER=kafka:9096
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=qwertyuiopo1
    depends_on:
      init-kafka:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - sdcc_progetto

  # ----------------------------
  # Sink Service (Go)
  # ----------------------------
  sink-service:
    build:
      context: .
      dockerfile: ./services/sink-service/Dockerfile
    container_name: sink_service
    restart: unless-stopped
    ports:
      - "50052:50052"
      - "2112"
    environment:
      - KAFKA_BROKER=kafka:9096
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-token
      - INFLUXDB_ORGANIZATION=sdcc_org
      - INFLUXDB_BUCKET=measurement
      - GRPC_PORT=50052
    depends_on:
      init-kafka:
        condition: service_completed_successfully
      init-influxdb:
        condition: service_completed_successfully
    networks:
      - sdcc_progetto

  # ----------------------------
  # Database Key-Value (Redis)
  # ----------------------------
  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "qwertyuiopo1", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "qwertyuiopo1", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./redis/data:/data
    restart: always
    networks:
      - sdcc_progetto

  # ----------------------------
  # Prometheus (scraping delle metriche)
  # ----------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Interfaccia Web di Prometheus
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - decision-service
      - sink-service
    networks:
      - sdcc_progetto


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - sdcc_progetto

networks:
  sdcc_progetto:
    driver: bridge
