prometheus:
  url: http://prometheus-service.sdcc-namespace.svc.cluster.local
  port: 9090

rules:
  default: false
  external:
    - seriesQuery: 'kafka_consumergroup_lag{consumergroup=~".+"}'
      resources:
        namespaced: false
      name:
        matches: "kafka_consumergroup_lag"
        as: "kafka_consumergroup_lag_by_group"
      metricsQuery: 'sum(avg_over_time(kafka_consumergroup_lag{<<.LabelMatchers>>}[1m])) by (consumergroup)'