apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ingestion-service-hpa
  namespace: sdcc-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ingestion-service
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Appena un Pod supera il 70% di 200m (140m CPU), ne crea un altro

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analyzer-service-hpa
  namespace: sdcc-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analyzer-service
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
# Richiede che decision-service abbia resources.requests.cpu definito
# nel suo Deployment, altrimenti l'HPA resta bloccato su stato <unknown>
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: decision-service-hpa
  namespace: sdcc-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: decision-service
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120  # evita di scendere di repliche troppo in fretta
      # se il carico oscilla durante il test